namespace SCLab.Enums
{
	public enum SCWeaponId
	{
		GaussRifleNormal = 0, // Marine
		GaussRifleJimRaynorMarine = 1,
		C10ConcussionRifleNormal = 2, // Ghost
		C10ConcussionRifleSarahKerrigan = 3,
		FragmentationGrenadeNormal = 4, // Vulture
		FragmentationGrenadeJimRaynorVulture = 5,
		SpiderMines = 6,
		TwinAutocannonsNormal = 7, // Goliath
		HellfireMissilePackNormal = 8, // Goliath
		TwinAutocannonsAlanSchezar = 9,
		HellfireMissilePackAlanSchezar = 10,
		ArcliteCannonNormal = 11, // Siege Tank
		ArcliteCannonEdmundDuke = 12,
		FusionCutter = 13, // SCV
		FusionCutterHarvest = 14,
		GeminiMissilesNormal = 15, // Wraith
		BurstLasersNormal = 16, // Wraith
		GeminiMissilesTomKazansky = 17,
		BurstLasersTomKazansky = 18,
		ATSLaserBatteryNormal = 19, // Battle Cruiser
		ATALaserBatteryNormal = 20, // Battle Cruiser
		ATSLaserBatteryNoradIIMengskDuGalle = 21,
		ATALaserBatteryNoradIIMengskDuGalle = 22,
		ATSLaserBatteryHyperion = 23,
		ATALaserBatteryHyperion = 24,
		FlameThrowerNormal = 25, // Firebat
		FlameThrowerGuiMontag = 26,
		ArcliteShockCannonNormal = 27, // Siege Tank
		ArcliteShockCannonEdmundDuke = 28,
		LongboltMissiles = 29, // ?? 20
		YamatoGun = 30,
		NuclearMissile = 31,
		Lockdown = 32,
		EMPShockwave = 33,
		Irradiate = 34,
		ClawsNormal = 35, // Zergling
		ClawsDevouringOne = 36,
		ClawsInfestedKerrigan = 37,
		NeedleSpinesNormal = 38, // Hydralisk
		NeedleSpinesHunterKiller = 39,
		KaiserBladesNormal = 40, // Ultralisk
		KaiserBladesTorrasque = 41,
		ToxicSporesBroodling = 42,
		Spines = 43, // Drone
		SpinesHarvest = 44,
		AcidSprayUnused = 45,
		AcidSporeNormal = 46, // Guardian
		AcidSporeKukulzaGuardian = 47,
		GlaveWurmNormal = 48, // Mutalisk
		GlaveWurmKukulzaMutalisk = 49,
		VenomUnusedDefiler = 50,
		VenomUnusedDefilerHero = 51,
		SeekerSpores = 52,
		SubterraneanTentacle = 53,
		SuicideInfestedTerran = 54,
		SuicideScourge = 55,
		Parasite = 56,
		SpawnBroodlings = 57,
		Ensnare = 58,
		DarkSwarm = 59,
		Plague = 60,
		Consume = 61,
		ParticleBeam = 62,
		ParticleBeamHarvest = 63,
		PsiBladesNormal = 64,
		PsiBladesFenixZealot = 65,
		PhaseDisruptorNormal = 66,
		PhaseDisruptorFenixDragoon = 67,
		PsiAssaultNormalUnused = 68,
		PsiAssaultTassadarAldaris = 69,
		PsionicShockwaveNormal = 70,
		PsionicShockwaveTassadarZeratulArchon = 71,
		Unknown72 = 72,
		DualPhotonBlastersNormal = 73,
		AntimatterMissilesNormal = 74,
		DualPhotonBlastersMojo = 75,
		AnitmatterMissilesMojo = 76,
		PhaseDisruptorCannonNormal = 77,
		PhaseDisruptorCannonDanimoth = 78,
		PulseCannon = 79,
		STSPhotonCannon = 80,
		STAPhotonCannon = 81,
		Scarab = 82,
		StasisField = 83,
		PsiStorm = 84,
		WarpBladesZeratul = 85,
		WarpBladesDarkTemplarHero = 86,
		MissilesUnused = 87,
		LaserBattery1Unused = 88,
		TormentorMissilesUnused = 89,
		BombsUnused = 90,
		RaiderGunUnused = 91,
		LaserBattery2Unused = 92,
		LaserBattery3Unused = 93,
		DualPhotonBlastersUnused = 94,
		FlechetteGrenadeUnused = 95,
		TwinAutocannonsFloorTrap = 96,
		HellfireMissilePackWallTrap = 97,
		FlameThrowerWallTrap = 98,
		HellfireMissilePackFloorTrap = 99,
		NeutronFlare = 100,
		DisruptionWeb = 101,
		Restoration = 102,
		HaloRockets = 103, // Valkyrie
		CorrosiveAcid = 104,
		MindControl = 105,
		Feedback = 106,
		OpticalFlare = 107,
		Maelstrom = 108,
		SubterraneanSpines = 109,
		GaussRifle0Unused = 110,
		WarpBladesNormal = 111,
		C10ConcussionRifleSamirDuran = 112,
		C10ConcussionRifleInfestedDuran = 113,
		DualPhotonBlastersArtanis = 114,
		AntimatterMissilesArtanis = 115,
		C10ConcussionRifleAlexeiStukov = 116,
		GaussRifle1Unused = 117,
		GaussRifle2Unused = 118,
		GaussRifle3Unused = 119,
		GaussRifle4Unused = 120,
		GaussRifle5Unused = 121,
		GaussRifle6Unused = 122,
		GaussRifle7Unused = 123,
		GaussRifle8Unused = 124,
		GaussRifle9Unused = 125,
		GaussRifle10Unused = 126,
		GaussRifle11Unused = 127,
		GaussRifle12Unused = 128,
		GaussRifle13Unused = 129,
		None = 130 // not use
	}
}
