using SCLab.Enums;

namespace SCLab.SCPlays
{
	public class SCTechSet(SCFileFormatVersion version)
	{
		public SCTech[] Techs { get; set; } = version switch
		{
			SCFileFormatVersion.StarCraft100 => [
				new SCTech(SCTechId.StimPacks),
				new SCTech(SCTechId.Lockdown),
				new SCTech(SCTechId.EMPShockwave),
				new SCTech(SCTechId.SpiderMines),
				new SCTech(SCTechId.ScannerSweep),
				new SCTech(SCTechId.SiegeMode),
				new SCTech(SCTechId.DefensiveMatrix),
				new SCTech(SCTechId.Irradiate),
				new SCTech(SCTechId.YamatoGun),
				new SCTech(SCTechId.CloakingField),
				new SCTech(SCTechId.PersonnelCloaking),
				new SCTech(SCTechId.Burrowing),
				new SCTech(SCTechId.Infestation),
				new SCTech(SCTechId.SpawnBroodling),
				new SCTech(SCTechId.DarkSwarm),
				new SCTech(SCTechId.Plague),
				new SCTech(SCTechId.Consume),
				new SCTech(SCTechId.Ensnare),
				new SCTech(SCTechId.Parasite),
				new SCTech(SCTechId.PsionicStorm),
				new SCTech(SCTechId.Hallucination),
				new SCTech(SCTechId.Recall),
				new SCTech(SCTechId.StasisField),
				new SCTech(SCTechId.ArchonWarp),
			],
			_ => [
				new SCTech(SCTechId.StimPacks),
				new SCTech(SCTechId.Lockdown),
				new SCTech(SCTechId.EMPShockwave),
				new SCTech(SCTechId.SpiderMines),
				new SCTech(SCTechId.ScannerSweep),
				new SCTech(SCTechId.SiegeMode),
				new SCTech(SCTechId.DefensiveMatrix),
				new SCTech(SCTechId.Irradiate),
				new SCTech(SCTechId.YamatoGun),
				new SCTech(SCTechId.CloakingField),
				new SCTech(SCTechId.PersonnelCloaking),
				new SCTech(SCTechId.Burrowing),
				new SCTech(SCTechId.Infestation),
				new SCTech(SCTechId.SpawnBroodling),
				new SCTech(SCTechId.DarkSwarm),
				new SCTech(SCTechId.Plague),
				new SCTech(SCTechId.Consume),
				new SCTech(SCTechId.Ensnare),
				new SCTech(SCTechId.Parasite),
				new SCTech(SCTechId.PsionicStorm),
				new SCTech(SCTechId.Hallucination),
				new SCTech(SCTechId.Recall),
				new SCTech(SCTechId.StasisField),
				new SCTech(SCTechId.ArchonWarp),
				new SCTech(SCTechId.Restoration),
				new SCTech(SCTechId.DisruptionWeb),
				new SCTech(SCTechId.Unused26),
				new SCTech(SCTechId.MindControl),
				new SCTech(SCTechId.DarkArchonMeld),
				new SCTech(SCTechId.Feedback),
				new SCTech(SCTechId.OpticalFlare),
				new SCTech(SCTechId.Maelstorm),
				new SCTech(SCTechId.LurkerAspect),
				new SCTech(SCTechId.Unused33),
				new SCTech(SCTechId.Healing),
				new SCTech(SCTechId.Unused35),
				new SCTech(SCTechId.Unused36),
				new SCTech(SCTechId.Unused37),
				new SCTech(SCTechId.Unused38),
				new SCTech(SCTechId.Unused39),
				new SCTech(SCTechId.Unused40),
				new SCTech(SCTechId.Unused41),
				new SCTech(SCTechId.Unused42),
				new SCTech(SCTechId.Unused43),
				]
		};
	}
}
