using SCLab.Enums;

namespace SCLab.SCPlays
{
	public class SCUpgradeSet(SCFileFormatVersion version)
	{
		public SCUpgrade[] Upgrades { get; set; } = version switch
		{
			SCFileFormatVersion.StarCraft100 => [
							new SCUpgrade(SCUpgradeId.TerranInfantryArmor),
				new SCUpgrade(SCUpgradeId.TerranVehiclePlating),
				new SCUpgrade(SCUpgradeId.TerranShipPlating),
				new SCUpgrade(SCUpgradeId.ZergCarapace),
				new SCUpgrade(SCUpgradeId.ZergFlyerCaparace),
				new SCUpgrade(SCUpgradeId.ProtossArmor),
				new SCUpgrade(SCUpgradeId.ProtossPlating),
				new SCUpgrade(SCUpgradeId.TerranInfantryWeapons),
				new SCUpgrade(SCUpgradeId.TerranVehicleWeapons),
				new SCUpgrade(SCUpgradeId.TerranShipWeapons),
				new SCUpgrade(SCUpgradeId.ZergMeleeAttacks),
				new SCUpgrade(SCUpgradeId.ZergMissileAttacks),
				new SCUpgrade(SCUpgradeId.ZergFlyerAttacks),
				new SCUpgrade(SCUpgradeId.ProtossGroundWeapons),
				new SCUpgrade(SCUpgradeId.ProtossAirWeapons),
				new SCUpgrade(SCUpgradeId.ProtossPlasmaShields),
				new SCUpgrade(SCUpgradeId.U238Shells),
				new SCUpgrade(SCUpgradeId.IonThrusters),
				new SCUpgrade(SCUpgradeId.BurstLasers),
				new SCUpgrade(SCUpgradeId.TitanReactor),
				new SCUpgrade(SCUpgradeId.OcularImplants),
				new SCUpgrade(SCUpgradeId.MoebiusReactor),
				new SCUpgrade(SCUpgradeId.ApolloReactor),
				new SCUpgrade(SCUpgradeId.ColossusReactor),
				new SCUpgrade(SCUpgradeId.VentralSacs),
				new SCUpgrade(SCUpgradeId.Antennae),
				new SCUpgrade(SCUpgradeId.PneumatizedCarapace),
				new SCUpgrade(SCUpgradeId.MetabolicBoost),
				new SCUpgrade(SCUpgradeId.AdrenalGlands),
				new SCUpgrade(SCUpgradeId.MuscularAugments),
				new SCUpgrade(SCUpgradeId.GroovedSpines),
				new SCUpgrade(SCUpgradeId.GameteMeiosis),
				new SCUpgrade(SCUpgradeId.MetasynapticNode),
				new SCUpgrade(SCUpgradeId.SingularityCharge),
				new SCUpgrade(SCUpgradeId.LegEnhancements),
				new SCUpgrade(SCUpgradeId.ScarabDamage),
				new SCUpgrade(SCUpgradeId.ReaverCapacity),
				new SCUpgrade(SCUpgradeId.GraviticDrive),
				new SCUpgrade(SCUpgradeId.SensorArray),
				new SCUpgrade(SCUpgradeId.GraviticBoosters),
				new SCUpgrade(SCUpgradeId.KhaydarinAmulet),
				new SCUpgrade(SCUpgradeId.ApialSensors),
				new SCUpgrade(SCUpgradeId.GraviticThrusters),
				new SCUpgrade(SCUpgradeId.CarrierCapacity),
				new SCUpgrade(SCUpgradeId.KhaydarinCore),
				new SCUpgrade(SCUpgradeId.UnknownUpgrade45)
						],
			_ => [
							new SCUpgrade(SCUpgradeId.TerranInfantryArmor),
				new SCUpgrade(SCUpgradeId.TerranVehiclePlating),
				new SCUpgrade(SCUpgradeId.TerranShipPlating),
				new SCUpgrade(SCUpgradeId.ZergCarapace),
				new SCUpgrade(SCUpgradeId.ZergFlyerCaparace),
				new SCUpgrade(SCUpgradeId.ProtossArmor),
				new SCUpgrade(SCUpgradeId.ProtossPlating),
				new SCUpgrade(SCUpgradeId.TerranInfantryWeapons),
				new SCUpgrade(SCUpgradeId.TerranVehicleWeapons),
				new SCUpgrade(SCUpgradeId.TerranShipWeapons),
				new SCUpgrade(SCUpgradeId.ZergMeleeAttacks),
				new SCUpgrade(SCUpgradeId.ZergMissileAttacks),
				new SCUpgrade(SCUpgradeId.ZergFlyerAttacks),
				new SCUpgrade(SCUpgradeId.ProtossGroundWeapons),
				new SCUpgrade(SCUpgradeId.ProtossAirWeapons),
				new SCUpgrade(SCUpgradeId.ProtossPlasmaShields),
				new SCUpgrade(SCUpgradeId.U238Shells),
				new SCUpgrade(SCUpgradeId.IonThrusters),
				new SCUpgrade(SCUpgradeId.BurstLasers),
				new SCUpgrade(SCUpgradeId.TitanReactor),
				new SCUpgrade(SCUpgradeId.OcularImplants),
				new SCUpgrade(SCUpgradeId.MoebiusReactor),
				new SCUpgrade(SCUpgradeId.ApolloReactor),
				new SCUpgrade(SCUpgradeId.ColossusReactor),
				new SCUpgrade(SCUpgradeId.VentralSacs),
				new SCUpgrade(SCUpgradeId.Antennae),
				new SCUpgrade(SCUpgradeId.PneumatizedCarapace),
				new SCUpgrade(SCUpgradeId.MetabolicBoost),
				new SCUpgrade(SCUpgradeId.AdrenalGlands),
				new SCUpgrade(SCUpgradeId.MuscularAugments),
				new SCUpgrade(SCUpgradeId.GroovedSpines),
				new SCUpgrade(SCUpgradeId.GameteMeiosis),
				new SCUpgrade(SCUpgradeId.MetasynapticNode),
				new SCUpgrade(SCUpgradeId.SingularityCharge),
				new SCUpgrade(SCUpgradeId.LegEnhancements),
				new SCUpgrade(SCUpgradeId.ScarabDamage),
				new SCUpgrade(SCUpgradeId.ReaverCapacity),
				new SCUpgrade(SCUpgradeId.GraviticDrive),
				new SCUpgrade(SCUpgradeId.SensorArray),
				new SCUpgrade(SCUpgradeId.GraviticBoosters),
				new SCUpgrade(SCUpgradeId.KhaydarinAmulet),
				new SCUpgrade(SCUpgradeId.ApialSensors),
				new SCUpgrade(SCUpgradeId.GraviticThrusters),
				new SCUpgrade(SCUpgradeId.CarrierCapacity),
				new SCUpgrade(SCUpgradeId.KhaydarinCore),
				new SCUpgrade(SCUpgradeId.UnknownUpgrade45),
				new SCUpgrade(SCUpgradeId.UnknownUpgrade46),
				new SCUpgrade(SCUpgradeId.ArgusJewel),
				new SCUpgrade(SCUpgradeId.UnknownUpgrade48),
				new SCUpgrade(SCUpgradeId.ArgusTalisman),
				new SCUpgrade(SCUpgradeId.UnknownUpgrade50),
				new SCUpgrade(SCUpgradeId.CaduceusReactor),
				new SCUpgrade(SCUpgradeId.ChitinousPlating),
				new SCUpgrade(SCUpgradeId.AnabolicSynthesis),
				new SCUpgrade(SCUpgradeId.CharonBooster),
				new SCUpgrade(SCUpgradeId.UnknownUpgrade55),
				new SCUpgrade(SCUpgradeId.UnknownUpgrade56),
				new SCUpgrade(SCUpgradeId.UnknownUpgrade57),
				new SCUpgrade(SCUpgradeId.UnknownUpgrade58),
				new SCUpgrade(SCUpgradeId.UnknownUpgrade59),
				new SCUpgrade(SCUpgradeId.UnknownUpgrade60),
			],
		};
	}
}
